language: node_js

notifications:
  email:
    on_success: change
    on_failure: change

node_js:
  - "6"
  - "8"
  - "10"
  - "node"

before_script: npm run devInstall

script: npm run buildall && npm run testall