language: node_js

notifications:
  email:
    on_success: change
    on_failure: change

node_js:
  - "6"
  - "8"
  - "10"
  - "node"

before_script: npm run devInstall

script: npm run buildall && npm run testall

deploy:
  provider: npm
  email: "YOUR_EMAIL_ADDRESS"
  api_key: "YOUR_AUTH_TOKEN https://docs.travis-ci.com/user/deployment/npm/#npm-auth-token"
  on:
    tags: true
